{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# import the necessary packages \n",
    "from wvgsolver import Cavity1D, UnitCell, Vec3, Waveguide\n",
    "from wvgsolver.geometry import BoxStructure, CylinderStructure, DielectricMaterial, MeshRegion\n",
    "from wvgsolver.utils import BBox\n",
    "from wvgsolver.engine import LumericalEngine\n",
    "\n",
    "import scipy.optimize\n",
    "import numpy as np\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "from waveguideSolver_funcs import *\n",
    "from cavity_sim_parameters import *\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Starting sim ===================================\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "True\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\LoncarGroup\\AppData\\Local\\Temp\\ipykernel_27296\\2037615619.py\", line 8, in <module>\n",
      "    sim_bandGap_rib(cavity_params,sim_params)\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\waveguideSolver_funcs.py\", line 1501, in sim_bandGap_rib\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\simulation\\base.py\", line 305, in simulate\n",
      "    raise err\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\simulation\\base.py\", line 277, in simulate\n",
      "    res = getattr(self, sim_type)(*args, **kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\simulation\\objects.py\", line 208, in _simulate_bandstructure\n",
      "    sweep = sess.run(FrequencySpectrum(BBox(\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\engine\\base.py\", line 114, in run\n",
      "    output = self.analyzers.analyze(self)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\analysis\\base.py\", line 8, in analyze\n",
      "    return self.callImplementation(\"analyze\", session, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\utils\\base.py\", line 12, in callImplementation\n",
      "    return getattr(self, fname)(session, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\Documents\\wvgsolver_sim\\waveguide_SiC_sim\\wvgsolver\\analysis\\procedures.py\", line 44, in _analyze_lumerical\n",
      "    field = f.pinch(f.getdata(name,comp))\n",
      "                    ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:/Program Files/Lumerical/v221/api\\python\\lumapi.py\", line 1153, in <lambda>\n",
      "    method = (lambda x: lambda self, *args: appCall(self, x, args))(name)\n",
      "                                            ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:/Program Files/Lumerical/v221/api\\python\\lumapi.py\", line 800, in appCall\n",
      "    raise LumApiError(message)\n",
      "lumapi.LumApiError: \"in getdata, the d-card named a49e27d0-a47b-41bd-9ee3-ca0a2f0b7d05 was not found.\\n  This is likely because you are in Layout Mode and need to switch to Analysis Mode by running the simulation\\n  or opening a simulation that contains data.\\n  Also, try the command '?getdata;' to see the which global d-cards are available.\"\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2102, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1310, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1199, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 1052, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 978, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 878, in format_record\n",
      "    frame_info.lines, Colors, self.has_colors, lvals\n",
      "    ^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\IPython\\core\\ultratb.py\", line 712, in lines\n",
      "    return self._sd.lines\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\stack_data\\core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\stack_data\\core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\stack_data\\utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\stack_data\\core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"c:\\Users\\LoncarGroup\\anaconda3\\envs\\wv_sol_env\\Lib\\site-packages\\executing\\executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "# debugging\n",
    "sim_params = cavity_sim_parameters.rib_sim_params\n",
    "cavity_params = cavity_sim_parameters.rib_cavity_params\n",
    "sim_params[\"save_fsps\"] = False\n",
    "sim_params[\"hide_GUI\"] = False\n",
    "sim_params['running_cluster'] = False\n",
    "sim_params['running_local'] = True\n",
    "sim_bandGap_rib(cavity_params,sim_params)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "wv_sol_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
